apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
      # 外部访问的接口
      port: 3308
      # pod服务接口
      targetPort: 3306
  type: LoadBalancer
  