apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      name: redis-server
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      